pipeline {
    agent any

    tools {
        maven 'Maven 3.6.1'
    }

    stages {
        stage('build') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Compiling the worker app'
                dir('worker') {
                     sh 'mvn compile'
                }
            }
        }
        stage('test') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Running the Unit tests on Worker app'
                dir('worker') {
                     sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                echo 'Packaging the worker app'
                dir('worker') {
                     sh 'mvn package -DskipTests'
                      archiveArtifacts artifacts: '**/target/*.jar',
                        allowEmptyArchive: true,
                        fingerprint: true,
                        onlyIfSuccessful: true
                }
            }
        }
    }
    
    post  {
        always {
            echo 'pipeline for worker run is completed'
        }
    }
}
