pipeline {
    agent any

    tools {
        maven 'Maven 3.6.1'
    }

    stages {
        stage('build') {
            steps {
                echo 'Compiling the worker app'
                dir('worker') {
                     sh 'mvn compile'
                }
            }
        }
        stage('test') {
            steps {
                echo 'Running the Unit tests on Worker app'
                dir('worker') {
                     sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            steps {
                echo 'Packaging the worker app'
                dir('worker') {
                     sh 'mvn package'
                }
            }
        }
    }
    
    post  {
        always {
            echo 'pipeline for worker run is completed'
        }
    }
}
