pipeline {
    agent {
        docker {
            image 'maven:3.6.1-jdk-8-alpine'
            args '-v $HOME/.m2:/root/.m2'
        }
    }

    stages {
        stage('build') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Compiling the worker app'
                dir('worker') {
                     sh 'mvn compile'
                }
            }
        }
        stage('test') {
            when {
                changeset "**/worker/**"
            }
            steps {
                echo 'Running the Unit tests on Worker app'
                dir('worker') {
                     sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            when {
                branch 'master'
                changeset "**/worker/**"
            }
            steps {
                echo 'Packaging the worker app'
                dir('worker') {
                     sh 'mvn package -DskipTests'
                      archiveArtifacts artifacts: '**/target/*.jar',
                        allowEmptyArchive: true,
                        fingerprint: true,
                        onlyIfSuccessful: true
                }
            }
        }

        stage('docker-package') {
            when {
                changeset "**/worker/**"
            }
            steps {
            echo 'Packaging the worker app with docker.'
            script {
                docker.withRegistry('https://index.docker.io/v1', 'dockerlogin') {
                    def workerImage = docker.build("rknmit/devops:v${env.BUILD_ID}", "./worker")
                    workerImage.push()
                    workerImage.push("${env.BRANCH_NAME}")
                }
            }
        }
    }
    
    post  {
        always {
            echo 'pipeline for worker run is completed'
        }
        failure {
            slackSend (channel: "instavote-cd", message: "Build Failed: ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")    
         }
        success {
            slackSend (channel: "instavote-cd", message: "Build Success: ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}
